# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'
source 'git@github.com:NimbleEdge/NimbleSDK-Podspecs.git'
target 'NimbleEdgeAI Assistant' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

   pod 'DeliteAI', :path => '/Users/nimbleedgeadmin/Desktop/NimbleEdge/folk/deliteAI-public/sdks/ios'
   pod 'lottie-ios'
   pod "MarkdownKit"
   pod 'Firebase/Core'
   pod 'FirebaseAnalytics'
   pod 'FirebaseCrashlytics'



end
